http:
  host: <%= process.env.HOST || 'localhost' %>
  port: <%= process.env.PORT || 3000 %>

db:
  mongo:
    url: mongodb://notify-mongodb:27017/notify-db

clients:
  redis:
    host: notify-redis
    port: 6379
    wildcards: true
  kafka:
    client:
      brokers:
        - 'notify-kafka:9092'
      ssl: false
      logLevel: 'INFO'
    consumer:
      groupId: 'notify'


logging:
  fileLogEnabled: true
  enabled:
    - health/health.controller.ts
    - health/health.service.ts

axios:
  config:
    repeats: 3
  client:

events:
  new-listeners: true
  remove-listeners: true

service:
  producers:
    gasu-dev-service:
      transports:
        - smtp

memory-heap: 100000

smtp:
  mail:
    host: <%= process.env.EMAIL_NODEMAILER_HOST || 'smtp.mail.ru' %>
    port: <%= process.env.EMAIL_NODEMAILER_PORT || 465 %>
    user: <%= process.env.EMAIL_NODEMAILER_USER %>
    pass: <%= process.env.EMAIL_NODEMAILER_PASS %>
    to: <%= process.env.EMAIL_NODEMAILER_CONSUMER || process.env.EMAIL_NODEMAILER_USER %>
