http:
  host: <%= process.env.HOST || 'localhost' %>
  port: <%= process.env.PORT || 3000 %>

db:
  mongo:
    url: mongodb://notify-mongodb:27017/notify-db

clients:
  redis:
    host: notify-redis
    port: 6379
    wildcards: true
  kafka:
    client:
      clientId: 'notify'
      brokers:
        - 'notify-kafka:9092'
      ssl: false
      logLevel: 'INFO'
    consumer:
      groupId: 'notify-consumer'


logging:
  fileLogEnabled: true
  jsonSerializeLevel: 3
  enabled:
    - core/events/events.service.ts
    - consumers/kafka/kafka.controller.ts
    - core/messages/messages.service.ts

axios:
  config:
    repeats: 3
  client:

events:
  new-listeners: true
  remove-listeners: true

service:
  producers:
    gasu-dev-all:
      transports: all
    gasu-dev-service:
      transports:
        - smtp

memory-heap: 100000

smtp:
  mail:
    host: <%= process.env.EMAIL_NODEMAILER_HOST || 'smtp.mail.ru' %>
    port: <%= process.env.EMAIL_NODEMAILER_PORT || 465 %>
    user: <%= process.env.EMAIL_NODEMAILER_USER %>
    pass: <%= process.env.EMAIL_NODEMAILER_PASS %>
    to-join-list: <%= process.env.EMAIL_NODEMAILER_CONSUMERS || process.env.EMAIL_NODEMAILER_USER %>

telegram:
  token: <%= process.env.TELEGRAM_TOKEN %>
  users-id-join-list: <%= process.env.TELEGRAM_USERS %>

test:
  producers:
    kafka: true
    redis: false